	{{ csrf_field() }}
	@foreach($data_form as $value)
		@switch($value['store'])
			@case('text')
				@include('admin.layouts.forms.text')
			@break
			@case('password')
				@include('admin.layouts.forms.password')
			@break
			@case('passwordGenerate')
				@include('admin.layouts.forms.passwordGenerate')
			@break
			@case('checkbox')
				@include('admin.layouts.forms.checkbox')
			@break
			@case('image')
				@include('admin.layouts.forms.image')
			@break
			@case('slides_image')
				@include('admin.layouts.forms.slides_image')
			@break
			@case('select')
				@include('admin.layouts.forms.select')
			@break
			@case('textarea')
				@include('admin.layouts.forms.textarea')
			@break
			@case('editor')
				@include('admin.layouts.forms.editor')
			@break
			@case('edit')
				@include('admin.layouts.forms.edit')
			@break
			@case('add')
				@include('admin.layouts.forms.add')
			@break
		@endswitch
	@endforeach
